import type { Station, TruckActivity } from './types';
import { GateInIcon, WeighbridgeIcon, GateOutIcon } from './components/icons';

export const initialStations: Station[] = [
  {
    id: 'gate-in',
    name: 'Gate In',
    icon: GateInIcon,
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1628153434751-2454a35368c1?q=80&w=800&auto=format&fit=crop',
    poNumber: 'PO-112233',
    sequence: '1/5',
    timestamp: '10.52',
    processStatus: 'Checking Documents',
    weight: null,
  },
  {
    id: 'wb-1',
    name: 'WB 1',
    icon: WeighbridgeIcon,
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1582209761386-7b28271131c9?q=80&w=800&auto=format&fit=crop',
    poNumber: 'PO-445566',
    sequence: '2/10',
    timestamp: '10.55',
    processStatus: 'Awaiting Tare',
    weight: '15.320 kg',
  },
  {
    id: 'wb-2',
    name: 'WB 2',
    icon: WeighbridgeIcon,
    status: 'Warning',
    image: null,
    poNumber: 'PO-778899',
    sequence: '4/8',
    timestamp: '10.58',
    processStatus: 'Final Weighing',
    weight: '28.710 kg',
  },
  {
    id: 'gate-out',
    name: 'Gate Out',
    icon: GateOutIcon,
    status: 'Idle',
    image: null,
    poNumber: null,
    sequence: null,
    timestamp: '--.--',
    processStatus: 'No Activity',
    weight: null,
  },
];

export const initialActivities: TruckActivity[] = [
  {
    id: '1',
    truckId: 'TRK-78912',
    status: 'Completed',
    timestamp: '10.52',
    location: 'Gate Out',
    poNumber: 'PO-101112',
    sequence: '7/7',
  },
  {
    id: '2',
    truckId: 'TRK-45601',
    status: 'Weighing',
    timestamp: '10.50',
    location: 'WB 2',
    poNumber: 'PO-778899',
    sequence: '4/8',
  },
  {
    id: '3',
    truckId: 'TRK-11234',
    status: 'Waiting',
    timestamp: '10.48',
    location: 'Gate In',
    poNumber: 'PO-112233',
    sequence: '1/5',
  },
  {
    id: '4',
    truckId: 'TRK-55678',
    status: 'In Progress',
    timestamp: '10.45',
    location: 'WB 1',
    poNumber: 'PO-445566',
    sequence: '2/10',
  },
    {
    id: '5',
    truckId: 'TRK-98765',
    status: 'Completed',
    timestamp: '10.42',
    location: 'Gate Out',
    poNumber: 'PO-998877',
    sequence: '5/5',
  },
];